name: release
on:
  push:
    branches:
      main

env:
  PORT: 3081

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cache
        uses: Swatinem/rust-cache@v2
        working-directory: axum_server
      - uses: taiki-e/install-action@just

      # - uses: JarvusInnovations/background-action@v1
      #   with:
      #     run: just prod &
      #     working-directory: axum_server
      #     wait-on: http://localhost:3081
      #     wait-for: 10m
      #     tail: true

      - uses: nickderobertis/background-task-action@v1
        with:
          run: cd axum_server && just prod > server.log 2>&1 &
      - name: Wait for server
        uses: iFaxity/wait-on-action
        with:
          resource: http://localhost:3081
      - name: run ssg
        run: just ssg
        working-directory: axum_server
      - name: Server log
        run: cat axum_server/server.log
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: axum_server/dist/
          retention-days: 10
          

