backend:
  name: git-gateway
  repo: michalvankodev/michalvankodev
  branch: master # Branch to update (optional; defaults to master)
  site_domain: michalvanko.dev

publish_mode: editorial_workflow
media_folder: 'static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: '_posts/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: true,
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          default: ['News'],
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Writers notes',
          name: 'notes',
          widget: 'markdown',
          required: false,
        }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Portfolio'
        name: 'portfolio'
        file: '_pages/portfolio.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Work history prelude,
              name: work_history_prelude,
              widget: markdown,
            }
          - label: Work history
            name: work_history
            widget: list
            fields:
              - { label: Company name, name: name, widget: string }
              - { label: Description, name: description, widget: markdown }
          - label: Projects
            name: projects
            widget: list
            fields:
              - { label: Project name, name: name, widget: string }
              - {
                  label: Displayed,
                  name: displayed,
                  widget: boolean,
                  default: true,
                }
              - { label: Description, name: description, widget: markdown }
              - label: Image
                name: image
                widget: object
                fields:
                  - {
                      label: Source,
                      name: source,
                      widget: image,
                      required: false,
                    }
                  - {
                      label: Image description,
                      name: image_description,
                      widget: string,
                      required: false,
                    }
          - label: Education
            name: education
            widget: list
            fields:
              - { label: Institution, name: name, widget: string }
              - {
                  label: Displayed,
                  name: displayed,
                  widget: boolean,
                  default: true,
                }
              - { label: Description, name: description, widget: markdown }
